---
version: "2"
services:
  server_survival:
    image: registry.gitlab.com/minetest/minetest/server:5.7.0
    user: root
    restart: always
    networks:
      - default
    volumes:
      - ./maps/survival:/root/.minetest/worlds/world
      - ./mods:/root/.minetest/worlds/world/worldmods:ro
      - ./config/survival.conf:/etc/minetest/minetest.conf:ro
    ports:
      - "30001:30001/udp"
      - "30001:30001/tcp"
  server_pvp:
    image: registry.gitlab.com/minetest/minetest/server:5.7.0
    user: root
    restart: always
    networks:
      - default
    volumes:
      - ./maps/pvp:/root/.minetest/worlds/world
      - ./mods:/root/.minetest/worlds/world/worldmods:ro
      - ./config/pvp.conf:/etc/minetest/minetest.conf:ro
    ports:
      - "30002:30002/udp"
      - "30002:30002/tcp"
